{% set name = "prefixed" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 135b93d4d18a2ca49243cc5b62f7a02969759e170135cd0121759f4a666cd369

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4,<4
    - pip
  run:
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4,<4

test:
  requires:
    - pip
  imports:
    - prefixed
  commands:
    - pip check

about:
  home: https://github.com/Rockhopper-Technologies/prefixed
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Prefixed alternative numeric library

extra:
  recipe-maintainers:
    - fcollonval
