{% set name = "prefixed" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81f4e3bc15046e772713ab80f08690e61c52cceb20141425754eab5b00b130c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4,<4
    - pip
  run:
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4,<4

test:
  requires:
    - pip
  imports:
    - prefixed
  commands:
    - pip check

about:
  home: https://github.com/Rockhopper-Technologies/prefixed
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Prefixed alternative numeric library

extra:
  recipe-maintainers:
    - fcollonval
